theme: jekyll-theme-time-machine
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <title> How about Lunch </title>
  <meta name="Generator" content="EditPlus">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <link rel="shortcut icon" href="https://www.easyicon.net/api/resizeApi.php?id=1226742&size=48" /> 
</head>

 <body>
  
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=shift_jis"/>
<meta http-equiv="Content-Language" content="ja-JP"/>  
<title>How about Lunchi</title>
<style type="text/css">
body {padding-top:100px;font:12px "\5B8B\4F53",sans-serif;text-align:center;background-color:#ffefe5;}
.result_box {margin:0 auto;width:700px;padding:100px 0;text-align:center;border:3px solid #FFFDE7;background: #ff8b8b;}
.result_box #oknum {width:700px;color:#FFFDE7;font-size:50pt;font-family:Verdana;text-align:center;border:none;background:#FF8B8B;}
.button_box {margin:50px 0 0 0;}
.button_box .btn {cursor:pointer;padding:0 30px;margin:0 10px;color:#555;font-family:"\5B8B\4F53",sans-serif;font-size:40px;}
</style>
</head>   
<body>
<script type="text/javascript">
//Lotery date
var alldata = "韓国料理,鬼,コンビニ,お弁当,和合餃子,坊主つけ麺,はなまるうどん,すきや,台湾料理,王将餃子,小諸そば,タイ料理,小四川,ダイエットしよう";  
var alldataarr = alldata.split(",");  
var num = alldataarr.length-1;
var timer;
function change(){   
	document.getElementById("oknum").value = alldataarr[GetRnd(0,num)];   
}
function start(){   
	clearInterval(timer);   
	timer = setInterval('change()',46); //random choice speed control,  faster < 46 < slower   
}
function ok(){   
	clearInterval(timer);   
	//the following content are already bingo,won't display again
	alldata = alldata.replace(document.getElementById("oknum").value,"").replace(",,",",");
	// cut start，and last,
	if (alldata.substr(0,1)==",")
	{
	  alldata = alldata.substr(1,alldata.length);
	}
	if (alldata.substr(alldata.length-1,1)==",")
	{
	  alldata = alldata.substring(0,alldata.length-1);
	}
	alldataarr = alldata.split(",");  
    num = alldataarr.length-1;	
}   
function GetRnd(min,max){   
	return parseInt(Math.random()*(max-min+1));   
}
</script>
<div class="result_box"><input type="text" id="oknum" name="oknum" value="Lunch will be ???" /></div>
<div class="button_box"><button class="btn" onclick="start()" accesskey="s">Start(<U>S</U>)</button><button class="btn" onclick="ok()" accesskey="g">Get!(<U>G</U>)</button></div>
</body>   
</html>
 </body>
</html>
